version: '3'

services:
  web:
    environment:
        - DOCKER_DEFAULT_PLATFORM=linux/amd64
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
